# Generated by Django 5.0.7 on 2024-08-10 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category_tag_blogpost_excerpt_blogpost_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
