# Generated by Django 3.2.25 on 2024-07-14 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='paintings/'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
