# Generated by Django 3.2.25 on 2024-07-24 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0002_auto_20240715_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='image',
            field=models.ImageField(default='paintings/placeholder.jpg', upload_to='paintings/'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='sku',
            field=models.CharField(default='bb8baf62', max_length=8, unique=True),
        ),
    ]
