# Generated by Django 3.2.25 on 2024-07-15 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0002_auto_20240714_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='sku',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
