# Generated by Django 3.2.25 on 2024-07-25 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0006_alter_painting_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='sku',
            field=models.CharField(default='e50347da', max_length=8, unique=True),
        ),
    ]
