# Generated by Django 3.2.25 on 2024-07-29 02:14

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0006_alter_painting_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='image',
            field=cloudinary.models.CloudinaryField(default='paintings/placeholder.jpg', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='sku',
            field=models.CharField(default='5a2fc17c', max_length=8, unique=True),
        ),
    ]
