# Generated by Django 3.2.25 on 2024-07-25 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0007_alter_painting_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='sku',
            field=models.CharField(default='7b1068cb', max_length=8, unique=True),
        ),
    ]
