# Generated by Django 3.2.25 on 2024-07-30 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0007_auto_20240729_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='sku',
            field=models.CharField(default='5448daca', max_length=8, unique=True),
        ),
    ]
