# Generated by Django 3.2.25 on 2024-08-01 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0008_alter_painting_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='sku',
            field=models.CharField(default='012a42e6', max_length=8, unique=True),
        ),
    ]
