# Generated by Django 5.0.7 on 2024-08-04 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0012_alter_painting_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='sku',
            field=models.CharField(default='eeb31062', max_length=8, unique=True),
        ),
    ]
