# Generated by Django 5.0.7 on 2024-08-06 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0013_alter_painting_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='sku',
            field=models.CharField(default='4cf23e62', max_length=8, unique=True),
        ),
    ]
