# Generated by Django 5.0.7 on 2024-08-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0014_alter_painting_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='sku',
            field=models.CharField(default='0ba0d88e', max_length=8, unique=True),
        ),
    ]
