# Generated by Django 5.0.7 on 2024-08-08 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0019_alter_painting_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='sku',
            field=models.CharField(default='aead4f04', max_length=8, unique=True),
        ),
    ]
