# Generated by Django 5.0.7 on 2024-08-10 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0024_alter_painting_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='sku',
            field=models.CharField(default='c34c433c', max_length=8, unique=True),
        ),
    ]
