# Generated by Django 5.0.7 on 2024-08-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0027_alter_painting_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='sku',
            field=models.CharField(default='6b95b5f5', max_length=8, unique=True),
        ),
    ]
