# Generated by Django 4.2 on 2024-10-01 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0028_alter_painting_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='sku',
            field=models.CharField(default='156b3e81', max_length=8, unique=True),
        ),
    ]
